spring:
     profiles:
       active: dev
     application:
       name: config_consumer_application_name
---
server:
  port: 1004
spring:
  profiles: dev
from: aa
---
server:
  port: 1005
spring:
  profiles: test
from: aa