spring:
     profiles:
       active: dev
     application:
       name: config_consumer_application_name
info:
  appName: config_consumer
  company: wangwei
  build.artifactId: $project.artifactId$
  build.version: $project.version$
---
spring:
  profiles: dev
from: aa
---
spring:
  profiles: test
from: aa